---
- hosts: ansible_clients
  become: yes
  become_user: root
  vars_files:
    - var/main_deploy.yml
  tasks:
  - name: Update Laravel project
    shell:
        "docker -H ssh://root@10.0.80.84:2022 exec -ti $(docker -H ssh://root@10.0.80.84:2022 ps | grep ecdock_php80 | awk '{print $1}') /mnt/laravel_update.sh {{ domain_name }}"
